db:
  image: postgres:10.4-alpine
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=configdb3test
    - POSTGRES_DB=configdb3test
    - POSTGRES_PASSWORD=configdb3test
  volumes:
    - ./data:/var/lib/postgresql/data
  mem_limit: "2048m"
  restart: always

configdb3:
  image: docker.lco.global/configdb3:test
  ports:
    - "8000:80"
  environment:
    - DB_HOST=db
    - DB_NAME=configdb3test
    - DB_USER=configdb3test
    - DB_PASS=configdb3test
    - DB_PORT=5432
    - SECRET_KEY=CHANGE_ME
    - DEBUG=true
    - OAUTH_CLIENT_ID=observation_portal_application_client_id
    - OAUTH_CLIENT_SECRET=observation_portal_application_client_secret
    - OAUTH_TOKEN_URL=http://observation-portal/o/token/
  mem_limit: "512m"
  restart: always
  links:
    - db:db
